### ISSUE TITLE
Cannot disable letsencrypt

### ISSUE THREAD

**Issue by fpoussin** [1Password/scim-examples#104]
Hi,

op-scim will start with letsencrypt mode enabled even when the flag is not passed, as long as I pass a previously generated scimsession file. Using the v1.4.2 docker image.

Valid scimsession file:
```
# /op-scim/op-scim --port=80 --redis-host=op-scim-bridge-redis-master --session=/secret/scimsession
[LOG] [1.0] 2020/06/23 15:27:25 (INFO) using host op-scim-bridge-redis-master for redis connection
[LOG] [1.0] 2020/06/23 15:27:25 (INFO) creating redis connection with address op-scim-bridge-redis-master:6379
[LOG] [1.0] 2020/06/23 15:27:25 (INFO) successfully connected to cache
[LOG] [1.0] 2020/06/23 15:27:25 (INFO) waiting for bearer token to begin provisioned user watcher
[LOG] [1.0] 2020/06/23 15:27:25 (INFO) requesting TLS certificate for domain "<hidden>"
[LOG] [1.0] 2020/06/23 15:27:25 (INFO) starting LetsEncrypt challenge server on :8080
[LOG] [1.0] 2020/06/23 15:27:25 (INFO) starting 1Password SCIM Bridge server on :8443
...
```

Empty session file: (expected behavior)
```
# /op-scim/op-scim --port=80 --redis-host=op-scim-bridge-redis-master --session=/test
[LOG] [1.0] 2020/06/23 15:26:33 (INFO) using host op-scim-bridge-redis-master for redis connection
[LOG] [1.0] 2020/06/23 15:26:33 (INFO) creating redis connection with address op-scim-bridge-redis-master:6379
[LOG] [1.0] 2020/06/23 15:26:33 (INFO) successfully connected to cache
[LOG] [1.0] 2020/06/23 15:26:33 (INFO) waiting for bearer token to begin provisioned user watcher
[LOG] [1.0] 2020/06/23 15:26:33 (INFO) Starting 1Password SCIM bridge server on :80
...
```

**Comment by alicethorne-ab** [comment]
Hello. Just to let you know, we're currently reviewing this issue internally to see how to best handle it going forward. Thank you for your patience.

**Comment by fpoussin** [comment]
Hello!
Do you have any update?
Thanks

**Comment by grellyd** [comment]
Hi @fpoussin! 

You can disable the LetsEncrypt server in one of two ways:
 - Remove the value from the `domain` field inside of the scimsession file.
 - Pass an empty domain flag like so: `-letsencrypt-domain=""`

We are looking at our default LetsEncrypt behaviour, so this may not be an issue in the future. 

As an aside, I see you are running version 1.0. I would recommend updating to a more recent version, as it contains a number of bug fixes and improvements detailed here: https://app-updates.agilebits.com/product_history/SCIM

Let me know if that works!

Graham

**Comment by fpoussin** [comment]
Thank you!

**Comment by grellyd** [comment]
You're welcome! You can also ping us at support@1password.com for more prompt help. We do not monitor these issues very closely.
