### ISSUE TITLE
404 on application using AWS TF

### ISSUE THREAD

**Issue by amandiwakar** [1Password/scim-examples#122]
Hi team, getting a 404 not found, everything seems to have deployed and installed correctly, the scimsession secret is accessible, LBs work, things look good, no other errors, redis and op-scim service are started successfully.

**Comment by amandiwakar** [comment]
Nov 10 07:35:42 op-scim-op-scim-scimtest op-scim[29878]: [LOG] [1.6.0] 2020/11/10 07:35:42 (INFO) [2020-11-10T07:35:42Z] RedisCache: healthy
Nov 10 07:35:42 op-scim-op-scim-scimtest op-scim[29878]: [LOG] [1.6.0] 2020/11/10 07:35:42 (INFO) [2020-11-10T07:35:37Z] SCIMServer: healthy
Nov 10 07:35:42 op-scim-op-scim-scimtest op-scim[29878]: [LOG] [1.6.0] 2020/11/10 07:35:42 (INFO) [2020-11-09T05:35:42Z] ProvisionWatcher: unknown
Nov 10 07:35:46 op-scim-op-scim-scimtest op-scim[29878]: [LOG] [1.6.0] 2020/11/10 07:35:46 (INFO) Handling GET: /ping

**Comment by amandiwakar** [comment]
Per: https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-binaryparam By default, the AWS CLI version 2 now passes all binary input and binary output parameters as base64-encoded strings. A parameter that requires binary input has its type specified as blob (binary large object) in the documentation. To pass binary data as a file to a CLI parameter, the AWS CLI version 2 enables you to specify the file using the following prefixes:

**Comment by pastjean** [comment]
Hi @amandiwakar, It seems like your server is receiving the `/ping` request. 
I suggest going through your official business support representative. We've got dedicated people to help you set this up. 

We're working hard exactly these days to make this AWS setup simpler and easier to deploy and operate. 

> Per: https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-binaryparam By default, the AWS CLI version 2 now passes all binary input and binary output parameters as base64-encoded strings. A parameter that requires binary input has its type specified as blob (binary large object) in the documentation. To pass binary data as a file to a CLI parameter, the AWS CLI version 2 enables you to specify the file using the following prefixes:

I do not understand what this comes play here. Can you please expand where this comes from ?

**Comment by alicethorne-ab** [comment]
Thank you for reporting this issue.

Can I ask where you're seeing the 404 from? I ask because the AWS/Terraform example does not serve the Web UI portion of the SCIM Bridge, and only serves the API paths.

You can more accurately test the SCIM Bridge's connectivity on AWS/Terraform using this `curl` command:

```bash
curl --header "Authorization: Bearer <bearertoken>" https://<domain>/scim/Users
```

**Comment by amandiwakar** [comment]
@pastjean the secretsmanager command is now AWS CLI V2 compatible. What's the ramification of receiving the /ping request, thats the SSM health checks, is something wrong with the way thats working that's causing the app to fail?

@alicethorne-ab , how do I setup the Web UI portion of the SCIM bridge if its not supported in the AWS/Terraform example? 

The curl returns --> {"detail":"401 (Unauthorized)","schemas":["urn:ietf:params:scim:api:messages:2.0:Error"]}

**Comment by alicethorne-ab** [comment]
Don't think this is relevant as of v2.3.0. The web UI should show up in all instances due to recent internal changes.
