### ISSUE TITLE
Azure Kubernetes Service deployment issue "http: TLS handshake error from <IP>:<PORT>: EOF"

### ISSUE THREAD

**Issue by kiss-less** [1Password/scim-examples#129]
Hello! Could you please help us find out the problem with the AKS deployment of the scim? We are using these configuration files to deploy the scim-bridge https://github.com/1Password/scim-examples/tree/master/kubernetes (the only change we made is the domain name https://github.com/1Password/scim-examples/blob/master/kubernetes/op-scim-config.yaml#L7 The deployment is successful, everything is running, however, we have a bunch of error messages from the op-scim-bridge pod:

```
2020/12/31 11:00:52 http: TLS handshake error from 10.244.2.1:9467: EOF
2020/12/31 11:00:55 http: TLS handshake error from 10.240.0.5:31516: EOF
2020/12/31 11:00:58 http: TLS handshake error from 10.244.2.1:5250: EOF
2020/12/31 11:01:01 http: TLS handshake error from 10.240.0.5:28929: EOF
2020/12/31 11:01:05 http: TLS handshake error from 10.244.2.1:17797: EOF
2020/12/31 11:01:07 http: TLS handshake error from 10.240.0.5:57041: EOF
2020/12/31 11:01:11 http: TLS handshake error from 10.244.2.1:25111: EOF
2020/12/31 11:01:13 http: TLS handshake error from 10.240.0.5:45293: EOF
2020/12/31 11:01:17 http: TLS handshake error from 10.244.2.1:1966: EOF
2020/12/31 11:01:19 http: TLS handshake error from 10.240.0.5:52336: EOF
2020/12/31 11:01:23 http: TLS handshake error from 10.244.2.1:6739: EOF
2020/12/31 11:01:25 http: TLS handshake error from 10.240.0.5:42490: EOF
```

We suspect that it might be related to the readiness\liveness probe from the LoadBalancer. What do you think?

**Comment by pastjean** [comment]
Hello @kiss-less, 

The readiness/liveness probe is on the pod side. It should not ping the ssl port as it doesn't support it. 
I suggest contacting support for help on this. We have people that will be able to book time with you to debug this (they'll also report to me if something is wrong in the code itself or the example)

**Comment by kiss-less** [comment]
Thanks @pastjean! Could you please clarify how can I reach out to the support?

**Comment by alicethorne-ab** [comment]
Hi all. I've created an internal ticket to investigate this issue in the near future. I'll let you all know when we have a fix available.

**Comment by rvanarkel** [comment]
I'm running into the exact same issue as @kiss-less. Did anyone found the solution for this?

**Comment by JigSawFr** [comment]
Hi there, we are experiencing the same problem on our side with Azure, is there a fix or a workaround ?

**Comment by alicethorne-ab** [comment]
Currently, the issue is mostly cosmetic and limited to noise in the logs, and doesn't affect the performance of the SCIM Bridge itself. However, we're working on a way of quieting down this noise in the future. If your SCIM Bridge is operating successfully, you can safely ignore the issue for now.

If you do end up having further issues with the SCIM Bridge, do feel free to reach out to Business Support.
