### ISSUE TITLE
aws-ecsfargate-terraform doesn't have the ELB target the Fargate cluster

### ISSUE THREAD

**Issue by jsvazic** [1Password/scim-examples#135]
Looking at the configuration for the ELB for the Terraform code, it seems that the target for the LB is empty.  The rest of the deployment seems to be working, but the health check is failing and there's nothing being re-directed by the LB.  Is there a missing rule from the terraform.tf file?

**Comment by jsvazic** [comment]
Interesting, it seems my Fargate containers are dying.  I'm trying to look into that next.

**Comment by accraw** [comment]
There is a listener and target group that serves this function. If you run into any issues (I know this reply is a little after the fact, hopefully you figured it out!) feel free to reach out to 1Password support.
