### ISSUE TITLE
AWS ECS Fargate Terraform - Feedback and tweaks

### ISSUE THREAD

**Issue by oscarmorasu** [1Password/scim-examples#137]
Today I tried the ECS + Fargate Terraform

## Feedback

First of all, excellent work. It was a breeze to setup. It worked the first time, even after several changes I did to match our internal best practices, it worked like a charm.

## Suggested tweaks

- Tags: Most organizations have a well defined taxonomy for tags. Define a `var.tags` variable that users can populate, and set it in all the resources supporting it.
- Default name prefix: Define variable `var.name_prefix`, and use it in all the resources where some name, name prefix or id is required:
- Specify the retention days of the log group

``` text
resource "aws_cloudwatch_log_group" "scim-bridge" {
  name = local.name_prefix
  tags = local.tags
  retention_in_days = 14
}

resource "aws_ecs_cluster" "scim-bridge" {
  name = local.name_prefix
  tags = local.tags
}

...
```

- Obtain the Zone ID from a data source: Instead of taking the Route53 Zone ID as a variable, use the domain to determine the Zone ID:

``` text
data "aws_route53_zone" "zone" {
  name         = var.domain // var.domain = example.com
  private_zone = false
}
```

- Obtain the VPC and subnets from a data source: Most organizations don't use the default VPC, and there's a VPC already setup.

``` text
# Find the vpc by name
data "aws_vpc" "vpc" {
  tags = {
    Name = "my-vpc-name"
  }
}

# Find the public subnets in the VPC
data "aws_subnet_ids" "subnets" {
  vpc_id = data.aws_vpc.vpc.id
  tags = { SubnetTier = "public"}
}
```

- Specify the VPC id when setting up the sec. groups:

``` text
resource "aws_security_group" "scim-bridge-sg" {
  vpc_id = data.aws_vpc.vpc.id
...
}
```

- Get the ACM certificate from a data source instead of creating a new one: Most organizations already have an ACM cert "*.example.com"

``` text
data "aws_acm_certificate" "scim_certificate" {
  domain = "*.${var.domain}"
}
```

**Comment by petr0sec** [comment]
@oscarmorasu these suggestions you documented here were EXTREMELY helpful in our deployment. Thank you for posting these!

**Comment by cgddrd-gardin** [comment]
These were excellent additions by @oscarmorasu - thanks very much.

**Comment by djpm05** [comment]
This also helped me out quite a bit, thank you for this!
