### ISSUE TITLE
Fix startup order when deploying with Docker Compose

### ISSUE THREAD

**Issue by devillecodes** [1Password/scim-examples#174]
Redis can take some time to start up. The problem is that the SCIM bridge startup fails if it cannot establish a connection to Redis. We should ensure that we give Redis enough time to start up before we attempt to launch the SCIM bridge.

On kubernetes the SCIM bridge will automatically be restarted on a failure, but we don't have that luxury with our Docker-based deployments.

Also, the `depends_on` option we currently rely on is not sufficient. Luckily the documentation describes some potential approaches to ensure the containers are started in the correct order, and with sufficient time for the applications to start up.

See [Control startup and shutdown order in Compose](https://docs.docker.com/compose/startup-order/) for more details.

**Comment by devillexio** [comment]
We do have a restart policy configured, but we should also consider putting more measures in place.
