### ISSUE TITLE
OS_REDIS_PASSWORD environment variable

### ISSUE THREAD

**Issue by marcusricardoaguiar** [1Password/scim-examples#210]
When deploying the scim with docker instances, it would be good to have an environment variable on scim.env called `OS_REDIS_PASSWORD` to allow using redis instances with authentication mechanism.

**Comment by ag-adampike** [comment]
Hey @marcusricardoaguiar! Thanks for filing this.

The `OP_REDIS_URL` should accept a connection string, i.e.:

```env
OP_REDIS_URL=rediss://:password@redis:6379
```

Does that solve this issue for you?

**Comment by marcusricardoaguiar** [comment]
> 

Hum, sounds good! Let me try that!

**Comment by ag-adampike** [comment]
@marcusricardoaguiar, I'm closing this as resolved, but please comment and re-open if there is still an issue. :-)
