### ISSUE TITLE
SCIM Bridge returning a 500 when I attempt to connect from Okta

### ISSUE THREAD

**Issue by davidwhite-edb** [1Password/scim-examples#247]
After resolving a slightly different [issue](https://github.com/1Password/scim-examples/issues/238#issuecomment-1675244481), The bridge is returning a 500 error when I try to connect to it to test my API Credentials. Additionally, after I deployed the bridge, 4 "health checks" show up green when I first login with my Bearer Token and view the scim dashboard at /app/status.

But after a few minutes, a couple more health checks appear, including the "ConfirmationWatcher" which shows as "Disconnected". I'm not sure how to resolve that problem.

**Comment by chasdl** [comment]
Hi @davidwhite-edb, can you share the logs that are generated when you attempt to connect? That should help us troubleshoot the issue. Is Provisioning enabled in your 1Password.com account, under Integrations -> User Provisioning -> "Provisioning users & groups"?

**Comment by davidwhite-edb** [comment]
I have reached out to an admin on our 1Password account, and we have confirmed that provisioning is not enabled yet. If that's the reason for the error(s), then we'll ignore them, and go through the process (as I noted an error log in the other issue on that topic) to finish turning on provisioning, but didn't put it together that the issues were related. Thank you!

**Comment by chasdl** [comment]
Ok, this makes sense then. The ConfirmationWatcher, which periodically looks for users to confirm (those who have been invited and have accepted their invite), will "fail" to do its job when it runs (every five minutes) and therefore will show up as Disconnected. I agree this isn't exactly intuitive, but everything sounds like it's working as intended.

**Comment by davidwhite-edb** [comment]
That makes sense. Thanks again.
I'm closing this as resolved.
