### ISSUE TITLE
Docker image for v0.9.2 missing from Docker Hub

### ISSUE THREAD

**Issue by jacobwgillespie** [1Password/scim-examples#26]
It looks like `v0.8.2` is the latest tag on Docker Hub and `v0.9.2` is not yet pushed: https://hub.docker.com/r/1password/scim/tags.

**Comment by cohix** [comment]
@jacobwgillespie we have temporarily pulled 0.9.2 while we investigate a potential issue. Please use 0.8.2 for now, and we'll re-publish 0.9.2 or a new 0.9.3 when the issue is resolved

**Comment by jacobwgillespie** [comment]
Cool, thanks for the fast response 👍
