### ISSUE TITLE
No CI/CD pipeline implemented for linting terraform & preforming security scans

### ISSUE THREAD

**Issue by sjbailey838** [1Password/scim-examples#271]
Hi there I'd just like to setup a CI/CD workflow using GHA to preform some security scanning & linting on PR's

**Comment by sjbailey838** [comment]
is this something this project would be interested in implementing? I'm just trying to get some experience contributing to open source projects. 

Thanks!

**Comment by plttn** [comment]
Hey there! Thanks for your feedback on this. While this repository is public, and we do accept community contributions, this repository is primarily maintained by 1Password employees. All new deployments and changes go through a review process internally that isn't necessarily surfaced in the PR history.

You're more than welcome to submit a PR if you'd like to see linting or similar added, however we can't make any promises for that PR being approved or not.

**Comment by sjbailey838** [comment]
Hi Jack, thanks for getting back to me! I'm fairly new so I'm just going
through the motions and trying to find a place I can learn :)

cheers!
-Steve
