### ISSUE TITLE
Document `OP_REDIS_*` variables

### ISSUE THREAD

**Issue by alicethorne-ab** [1Password/scim-examples#278]
As part of `v2.8.5`, the environment variables related to `redis` were undeprecated and reintroduced as configuration options. We need to document those variables.

These include:

* `OP_REDIS_HOST` - setting the `redis` hostname (i.e: `localhost`)
* `OP_REDIS_PORT` - setting the `redis` port (i.e: `6379`)
* `OP_REDIS_USERNAME` - setting the username used to connect to `redis` (i.e: `admin`)
* `OP_REDIS_PASSWORD` - setting the password used to connect to `redis` (i.e: `hunter2`)
* `OP_REDIS_SSL_ENABLED` - setting whether the connection should be SSL-enabled (`0` or `1` (boolean))
* `OP_REDIS_INSECURE_SSL` - setting whether insecure SSL connections should be allowed when `OP_REDIS_SSL_ENABLED` is also enabled (`0` or `1` (boolean))

Also of note is that a user must _unset_ `OP_REDIS_URL` for these to be used. In other words, if `OP_REDIS_URL` is set, none of the other `OP_REDIS_*` variables will be used.

**Comment by scottisloud** [comment]
For the moment, I'll set all configuration manifests to continue to use OP_REDIS_URL, since that's the most common way people will continue to deploy the bridge. I'll include example-specific documentation and add the variables to the manifests empty/commented out/etc where possible.

**Comment by alicethorne-ab** [comment]
`OP_REDIS_INSECURE_SSL` has been implemented as of `v2.9.0` and can be included in documentation now. 🙂
