### ISSUE TITLE
Issue deploying on Google Cloud Run

### ISSUE THREAD

**Issue by max-henri** [1Password/scim-examples#309]
Hello,
I am getting this error when trying to deploy the SCIM bridge on Google Cloud Run

```
{
  "textPayload": "Default STARTUP TCP probe failed 1 time consecutively for container \"scim\" on port 3002. The instance was not started.",
  "insertId": "66546baa000ef654df0930ba",
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "configuration_name": "op-scim-bridge",
      "location": "us-central1",
      "project_id": "one-password-bridge-400219",
      "revision_name": "op-scim-bridge-00002-q79",
      "service_name": "op-scim-bridge"
    }
  },
  "timestamp": "2024-05-27T11:16:58.980564Z",
  "severity": "ERROR",
  "labels": {
    "instanceId": "00f46b92854f18f9553ea62640ce170792ee0ec39f87d188799d310cefc76349ae7c166621dd7fa637f515f13d0ed03edb73ad764612d7c26c764b75eced053bb127",
    "container_name": "scim"
  },
  "logName": "projects/one-password-bridge-400219/logs/run.googleapis.com%2Fvarlog%2Fsystem",
  "receiveTimestamp": "2024-05-27T11:16:58.986717572Z"
}

```

**Comment by ag-adampike** [comment]
Hi @max-henri. Apologies for the delay and thanks for your patience.

After what step are you seeing this error? I am assuming it is the deployment command:

https://github.com/1Password/scim-examples/blob/7740dbc8fe2af6acb80f66c0a74671ef66aeec0a/beta/google-cloud-run/README.md?plain=1#L87-L91

Is that correct? Is there anything else you can share about the steps you took and where things went awry?

**Comment by max-henri** [comment]
Thank you @ag-adampike 
Indeed, it is after that step.
If that's helpful (knowing this is still a beta), we could schedule a session to try together.

**Comment by ag-adampike** [comment]
Yes, I'd love to take you up on that if we can arrange it. 🍻

Could you please write in to support@1password.com and reference this issue?

In the meantime, I'll try to reproduce this and find the root cause.
