### ISSUE TITLE
New DO App Platform API/CLI Slugs

### ISSUE THREAD

**Issue by MrCoBalt** [1Password/scim-examples#315]
It appears that rather than `basic-xxs` DigitalOcean is now expecting the values listed here: https://docs.digitalocean.com/products/app-platform/details/pricing/ (as of May 2024).

I haven't tested just yet, but it seems that `apps-s-1vcpu-0.5gb` should be the new value for future DO deployments, replacing lines like so in the yaml files:
https://github.com/1Password/scim-examples/blob/f1878fd39de99df36bb5786e71487ef2d74a3dce/do-app-platform-op-cli/op-scim-bridge.yaml#L16

Thanks!

**Comment by ag-adampike** [comment]
Hey @MrCoBalt! Thanks for bringing this to our attention.

We'll take a look soon and adjust accordingly. :-)
