### ISSUE TITLE
Getting error  'missing provider provider.us-east-1`

### ISSUE THREAD

**Issue by devator-22** [1Password/scim-examples#81]
I get error **'missing provider provider.us-east-1`** 

when running  **' terraform plan -out=/tmp/op-scim.plan`**

**Comment by cohix** [comment]
@ag-andrey05 any insight here?

**Comment by ag-andrey05** [comment]
it has to match with what is configured in here https://github.com/1Password/scim-examples/blob/94aac1e809df2fd5dc7ac4350d78e1561d88596b/aws-terraform/terraform/deploy/example_env/providers.tf#L5 the alias

**Comment by devator-22** [comment]
Thanks this is succesful now when running **terraform plan**  But I am now getting a different error when running **terraform apply**

<img width="715" alt="Screen Shot 2019-10-30 at 3 52 18 PM" src="https://user-images.githubusercontent.com/54195350/67893618-46b6dc80-fb2d-11e9-9cb0-31bd20fee098.png">

I have changed the region on variables.tf but still getting the error
<img width="687" alt="Screen Shot 2019-10-30 at 3 54 30 PM" src="https://user-images.githubusercontent.com/54195350/67893805-aca36400-fb2d-11e9-932e-51895f97bcd1.png">

**Comment by ag-andrey05** [comment]
Hi @devator-22,

is this still present in your code: 
https://github.com/1Password/scim-examples/blob/94aac1e809df2fd5dc7ac4350d78e1561d88596b/aws-terraform/terraform/deploy/example_env/main.tf#L11

https://github.com/1Password/scim-examples/blob/94aac1e809df2fd5dc7ac4350d78e1561d88596b/aws-terraform/terraform/deploy/example_env/main.tf#L30 ?

**Comment by devator-22** [comment]
Yes, they are both present

**Comment by devator-22** [comment]
Both present but still getting the error 
<img width="617" alt="Screen Shot 2019-11-01 at 1 31 05 PM" src="https://user-images.githubusercontent.com/54195350/68043555-edc18280-fcab-11e9-8d4b-4fbd45fa64ed.png">

**Comment by devator-22** [comment]
Any insights were the problem could be?

**Comment by ag-andrey05** [comment]
@devator-22 , we'll take a look & get back to you in a bit, thank you.

**Comment by devator-22** [comment]
I was able to resolve it by commenting out the account alias on providers.tf and updating main.tf accordingly
<img width="375" alt="Screen Shot 2019-11-04 at 11 11 31 AM" src="https://user-images.githubusercontent.com/54195350/68136822-e68cb580-fef3-11e9-8a05-de1b1adeeb3f.png">

**Comment by ag-andrey05** [comment]
@devator-22 glad you resolved the issue.

we tested our code again just to troubleshoot this issue and can confirm that if `region` is consistently set then terraform code is executed without any issues:

providers.tf:
```hcl
provider "aws" {
  region              = var.region
  allowed_account_ids = [var.aws-account]
  alias               = "us-east-2"

<redacted>

terraform {
  required_version = ">= 0.12"

  backend "s3" {
    region = "us-east-2" 
<redacted>
```

variables.tf:
```hcl
<redacted>

variable "region" {
  type        = string
  description = "AWS region where the application is deployed, for example 'us-east-2'"
  default     = "us-east-2"
}

<redacted>
```

main.tf:
```hcl

module "infra" {
  source = "../../module_scim_infra/"

  providers = {
    "aws" = "aws.us-east-2"
  }

<redacted>

module "scim-app" {
  source = "../../module_scim_app/"

  providers = {
    "aws" = "aws.us-east-2"
  }

<redacted>
```

Please let us know if you have any questions.

**Comment by devator-22** [comment]
Thanks fro your help!
