### ISSUE TITLE
v1.1.1 User add errors synching to AzureAD

### ISSUE THREAD

**Issue by cbadke** [1Password/scim-examples#82]
I recently upgraded my SCIM to v1.1.1 from docker hub and we immediately noticed errors when new users were being synched. I rolled back to version v1.0 (skipped v1.1.0 since it was only up for 2 days and assumed it was bad) and synch for my added users seems to work.

From Azure:
> ACTIVITY TYPE
> Export
>  
> CATEGORY
> ApplicationManagement
>  
> STATUS
> Failure
>  
> STATUS REASON
> Failed to create User 'xxxxxx@xxxxxxxxx.com' in customappsso; Error: The SCIM endpoint is not fully compatible with the Azure Active Directory SCIM client. Please refer to the Azure Active Directory SCIM provisioning documentation and adapt the SCIM endpoint to be able to process provisioning requests from Azure Active Directory.
> StatusCode: BadRequest
> Message: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
> Web Response: Bad Request . This operation was retried 0 times. It will be retried again after this date: 2019-10-30T15:13:17.6715300Z UTC
>  
>  
> ErrorCode
> SystemForCrossDomainIdentityManagementBadRequest
>  
> EventName
> EntryExportAdd
>  
> Type:
> ServicePrincipal
>  
> DISPLAY NAME
> 1Password SCIM
>  
> TARGET
>  
> TYPE
> User

Let me know if there are any other details you need.

**Comment by cohix** [comment]
@cbadke could you get the logs from the SCIM container itself so we can see what errors were created? You can email support+business@agilebits.com with the logs attached and then post your ticket ID back here so that I can find it.

**Comment by cbadke** [comment]
Can you provide guidance on where to find them?

**Comment by cohix** [comment]
It all depends on where you deployed, if you're using docker, then the `docker logs` command would be your friend, if it's k8s then `kubectl logs`

**Comment by cbadke** [comment]
No response was sent. Does the mail system block attachments?

**Comment by cohix** [comment]
No it certainly shouldn't.

**Comment by grellyd** [comment]
Hi @cbadke 

I got the email and have responded. We will get to the bottom of what is going wrong. 

I am closing this issue in favour of the email support.
