### ISSUE TITLE
Consider supporting redis sentinel

### ISSUE THREAD

**Issue by SEJeff** [1Password/scim-examples#88]
We run this scim bridge in kubernetes and would like to use a highly available redis instance. The k8s [redis-operator](https://github.com/spotahome/redis-operator) makes this trivial, but to use it properly, the application needs to be sentinel aware. This allows having a master redis and 2 read-only slaves ensuring uninterrupted availability when a node gets evicted due to hardware problems or whatnot.

**Comment by cohix** [comment]
Thanks for the feedback :) I rarely hear of anyone running redis sentinel in production, so this is the first request I've heard for it.

**Comment by SEJeff** [comment]
It is the most sensible way to reliably run HA redis in kuberntes. I'm sure there are plenty of other people using it as the default redis-operator config spins up three sentinel pods. It would be very much appreciated if the scim bridge we use for production supported this!

**Comment by accraw** [comment]
We've added a ticket to our backlog, thank you for the request!
