### ISSUE TITLE
Update Terraform README for AWS CLI version 2 functionality

### ISSUE THREAD

**Issue by chad-fox** [1Password/scim-examples#98]
When using the AWS CLI version 2, the following parameter is needed:

`--cli-binary-format raw-in-base64-out`

scim-examples/aws-terraform/README.md Example:
> aws secretsmanager create-secret --name op-scim/scimsession --secret-binary file:///path/to/scimsession --region <aws_region>

Updated example:
> aws secretsmanager create-secret --name op-scim/scimsession --secret-binary file:///path/to/scimsession --region <aws_region> --cli-binary-format raw-in-base64-out

Otherwise, the following error is presented:
> Invalid base64: "{...

**Comment by cohix** [comment]
@alicethorne-ab could you take a look at this please ?

@chad-fox thanks for reporting!

**Comment by alicethorne-ab** [comment]
I'll look into getting this bug fixed soon. Thank you for reporting!
